            - name: Zip extract
  # You may pin to the exact commit or the version.
  # uses: hoatruongdev09/extract-zip@dd1eb7883f2792b2baeb525abd0471439e1c6a4e
  uses: hoatruongdev09/extract-zip@v1.2
  with:
    # zip file path
    input-path: 
    # extract folder path
    output-path: 
          
